name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          pwd

