name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix: 
        node-version: [12.x]

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/osboxes/nodejs-githubactions/nodejs-on-ec2
          git pull origin master
          npm ci
          npm start

